### ISSUE TITLE
About the testing categories

### ISSUE THREAD

**Issue by robottrainingacademy** [visipedia/iwildcam_comp#2]
According to Wikipedia, The elk or wapiti (Cervus canadensis) is one of the largest species within the deer family.[1]
Rodents (from Latin Rodere, "to gnaw") are mammals of the order Rodenti[2]. I feel like the problem is not well defined. They are very similar or in the same category. Should you guys modify it?

[1]https://en.wikipedia.org/wiki/Elk
[2]https://en.wikipedia.org/wiki/Rodent

**Comment by robottrainingacademy** [comment]
For the species called "elk" in Eurasia (Alces alces), see Moose.[2]
Like what I can tell in the test set categories, they are very similar and people are actually reference different names to the same thing. Maybe some of the categories could be merged? 
[2]https://en.wikipedia.org/wiki/Rodent

**Comment by robottrainingacademy** [comment]
For the species called "elk" in Eurasia (Alces alces), see Moose.[2]
So for moose and elk, they are very similar and people are actually referencing these two different names to the same thing. Maybe some of the categories could be merged? They are not apparently different animals like "cat" and "dog".
[2]https://en.wikipedia.org/wiki/Rodent

**Comment by luuckiest** [comment]
Also, how do you define small_mammals? All mammals that are small?

**Comment by beerys** [comment]
The definitions of the classes and how they map into the taxonomic tree is defined in the iNaturalist taxonomy mapping file.  

"deer" in this case refers explicitly to any species under the genus _Odocoileus_
"elk" is only the species _Cervus canadensis_
"moose" is only the species _Alces alces_
"small mammal" is anything within the order _Rodentia_

If you have any other questions about the taxonomic mapping, please refer to the taxonomic map provided.
