### ISSUE TITLE
Explanation of the available datasets

### ISSUE THREAD

**Issue by tom-bu** [visipedia/iwildcam_comp#3]
Is the larger IDFG images and annotation the same as the smaller one? Is this the test set or does IDFG include more data with labels? 

Also what is the iNat taxa map? Is that related to the iNat Idaho images and annotations?

**Comment by tom-bu** [comment]
If I understand it correctly, the IDFG images do not include any more category annotations than what is available. The annotations only refer to location and time data. 

And the iNat taxa map just specifies the genus species of each category in the entire iNat set.

**Comment by beerys** [comment]
The IDFG images are the test set, so no, we do not provide the correct labels for that data.  The iNat taxa map is provided to help users if that want to take advantage of additional iNaturalist data in the competition, which is allowed.
