### ISSUE TITLE
Inquiry about CCT Dataset

### ISSUE THREAD

**Issue by eslambakr** [visipedia/iwildcam_comp#5]
I have a question about Dataset and according to #3 I know that IDFG dataset it is for testing not for training but what about CCT ?

And Is it different than the original data set which provided on Kaggle?

And here you said that "We have run the detector over the three datasets, and provide the top 100 boxes and associated confidences", what do you mean by the "Three datasets" ?

**Comment by beerys** [comment]
The CCT dataset here and on kaggle are the same, CCT is for training.  By "the three datasets" I mean CCT, Inat_Idaho (also available for use as training data), and IDFG.
