### ISSUE TITLE
ids in detection results

### ISSUE THREAD

**Issue by saikatdutta** [visipedia/iwildcam_comp#6]
What are image ids in detection results file? I was looking into the detection results file for iNat idaho. There, ids were not same as filenames. So, what is the significance of the ids?

**Comment by beerys** [comment]
They have no significance, just are a way to uniquely identify the files.

**Comment by saikatdutta** [comment]
So, how do I know which id corresponds to which file?

**Comment by beerys** [comment]
The id and the filename are linked in the IDFG metadata file.

**Comment by saikatdutta** [comment]
Yeah, I got this. It's in image dictionary in the json file. Thanks.
