### ISSUE TITLE
Links for iWildCam 2018 seem to be broken

### ISSUE THREAD

**Issue by alessandro-montanari** [visipedia/iwildcam_comp#9]
Hi, 
when I try any link on the 2018 edition challenge I get this error:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
There is an account problem for the requested project.
</Details>
</Error>
```

Is there any way to download these files?
Thanks

**Comment by beerys** [comment]
Thanks for pointing this out! I'll look into it and figure out what went wrong.

**Comment by beerys** [comment]
The files were being hosted by Google, and it looks as though they've possibly removed access (I wasn't informed). I'll reach out to them and see if I can get the links back up. In the meantime, all the images from the competition are available at http://lila.science/datasets/caltech-camera-traps.

**Comment by alessandro-montanari** [comment]
Thanks for the link.
Do you also have alternative links for the train/val/test splits used in the challenge?
Thanks!
